var compressionMethods = [
        "Store",
        "Shrunk",
        "Reduced with compression factor 1",
        "Reduced with compression factor 2",
        "Reduced with compression factor 3",
        "Reduced with compression factor 4",
        "Implode",
        "Tokenizing",
        "Deflate",
        "Deflate64",
        "PKWARE Data Compression Library Imploding",
        "",                //Reserved by PKWARE
        "BZIP2",
        "",                //Reserved by PKWARE
        "LZMA",
        "",                //Reserved by PKWARE
        "",                //Reserved by PKWARE
        "",                //Reserved by PKWARE
        "IBM TERSE",
        "IBM LZ77",
        "WavPacked",
        "PPMd"
];
var versionMadeBy = [
        "MS-DOS",
        "Amiga",
        "OpenVMS",
        "UNIX",
        "VM/CMS",
        "Atari ST",
        "OS/2 H.P.F.S.",
        "Macintosh",
        "Z-System",
        "CP/M",
        "Windows NTFS",
        "MVS (OS/390 - Z/OS)",
        "VSE",
        "Acorn Risc",
        "VFAT",
        "alternate MVS",
        "BeOS",
        "Tandem",
        "OS/400",
        "OS/X"
];

var keyCodes = {
    8: "Backspace",
    9: "Tab",
    13: "Enter",
    16: "Shift",
    17: "Ctrl",
    18: "Alt",
    19: "Pause",
    20: "Caps_Lock",
    27: "Esc",
    32: "Space",
    33: "Page_Up",
    34: "Page_Down",
    35: "End",
    36: "Home",
    37: "Arrow_Left",
    38: "Arrow_Up",
    39: "Arrow_Right",
    40: "Arrow_Down",
    45: "Insert",
    46: "Delete",
    48: "0",
    49: "1",
    50: "2",
    51: "3",
    52: "4",
    53: "5",
    54: "6",
    55: "7",
    56: "8",
    57: "9",
    59: ";",
    61: "=",
    65: "a",
    66: "b",
    67: "c",
    68: "d",
    69: "e",
    70: "f",
    71: "g",
    72: "h",
    73: "i",
    74: "j",
    75: "k",
    76: "l",
    77: "m",
    78: "n",
    79: "o",
    80: "p",
    81: "q",
    82: "r",
    83: "s",
    84: "t",
    85: "u",
    86: "v",
    87: "w",
    88: "x",
    89: "y",
    90: "z",
    91: "Windows",
    92: "Windows",
    93: "Menu",
    112: "F1",
    113: "F2",
    114: "F3",
    115: "F4",
    116: "F5",
    117: "F6",
    118: "F7",
    119: "F8",
    120: "F9",
    121: "F10",
    122: "F11",
    123: "F12",
    186: ";",
    187: "=",
    188: ",",
    189: "-",
    190: ".",
    191: "/",
    192: "'",
    219: "[",
    220: "\\",
    221: "]",
    222: "#",
    223: "`"
};

var dangerousCombinations = {
	"Ctrl + f": "Search Page",
	"Ctrl + d": "Add bookmark",
	"Ctrl + r": "Refresh Page",
	"F5": "Refresh Page",
	"Ctrl + u": "View Source",
	"Ctrl + o": "Open Webpage",
	"Ctrl + s": "Save Webpage",
	"Ctrl + j": "View download history",
	"Ctrl + b": "Show/Hide Bookmark Toolbar",
	"Ctrl + -": "Zoom Out",
	"Ctrl + =": "Zoom In",
	"Ctrl + p": "Print",
	"Alt + d": "Select Address Bar",
	"Alt + l": "Select Address Bar",
	"Alt + Arrow_Left": "Go Back",
	"Alt + Arrow_Right": "Go Forward",
	"Shift + Esc": "Task Manager",
	"Alt + d": "Select Address Bar"
};
var keyCodes = {
	8: "Backspace",
	9: "Tab",
	13: "Enter",
	16: "Shift",
	17: "Ctrl",
	18: "Alt",
	19: "Pause",
	20: "Caps_Lock",
	27: "Esc",
	32: "Space",
	33: "Page_Up",
	34: "Page_Down",
	35: "End",
	36: "Home",
	37: "Arrow_Left",
	38: "Arrow_Up",
	39: "Arrow_Right",
	40: "Arrow_Down",
	45: "Insert",
	46: "Delete",
	48: "0",
	49: "1",
	50: "2",
	51: "3",
	52: "4",
	53: "5",
	54: "6",
	55: "7",
	56: "8",
	57: "9",
	59: ";",
	61: "=",
	65: "a",
	66: "b",
	67: "c",
	68: "d",
	69: "e",
	70: "f",
	71: "g",
	72: "h",
	73: "i",
	74: "j",
	75: "k",
	76: "l",
	77: "m",
	78: "n",
	79: "o",
	80: "p",
	81: "q",
	82: "r",
	83: "s",
	84: "t",
	85: "u",
	86: "v",
	87: "w",
	88: "x",
	89: "y",
	90: "z",
	91: "Windows",
	92: "Windows",
	93: "Menu",
	112: "F1",
	113: "F2",
	114: "F3",
	115: "F4",
	116: "F5",
	117: "F6",
	118: "F7",
	119: "F8",
	120: "F9",
	121: "F10",
	122: "F11",
	123: "F12",
	186: ";",
	187: "=",
	188: ",",
	189: "-",
	190: ".",
	191: "/",
	192: "'",
	219: "[",
	220: "\\",
	221: "]",
	222: "#",
	223: "`"
};

function isDangerousCombination(combination) {
	return dangerousCombinations[combination] || false;
};

function duplicateShortcut(value, array) {
	array = array || localStorage;
	var duplicate = false;
	for (i in array) {
		duplicate = localStorage[i] === value;
		if (duplicate) break;
	}
	return duplicate;
};


var Keyboard = '<div id="top_row" class="row"><div id="Esc" class="s_key">Esc</div><div class="key_gap"></div><div class="f_key">F1</div><div class="f_key">F2</div><div class="f_key">F3</div><div class="f_key">F4</div><div class="key_gap"></div><div class="f_key">F5</div><div class="f_key">F6</div><div class="f_key">F7</div><div class="f_key">F8</div><div class="key_gap"></div><div class="f_key">F9</div><div class="f_key">F10</div><div class="f_key">F11</div><div class="f_key">F12</div></div><div class="row"><div class="key">¬</div><div class="key">1</div><div class="key">2</div><div class="key">3</div><div class="key">4</div><div class="key">5</div><div class="key">6</div><div class="key">7</div><div class="key">8</div><div class="key">9</div><div class="key">0</div><div class="key">-</div><div class="key">=</div><div id="Backspace" class="s_key">Backspace</div></div><div class="row"><div id="Tab" class="s_key">Tab</div><div class="key">Q</div><div class="key">W</div><div class="key">E</div><div class="key">R</div><div class="key">T</div><div class="key">Y</div><div class="key">U</div><div class="key">I</div><div class="key">O</div><div class="key">P</div><div class="key">[</div><div class="key">]</div></div><div class="row"><div id="Caps_Lock" class="s_key">Caps Lock</div><div class="key">A</div><div class="key">S</div><div class="key">D</div><div class="key">F</div><div class="key">G</div><div class="key">H</div><div class="key">J</div><div class="key">K</div><div class="key">L</div><div class="key">;</div><div class="key">\'</div><div class="key">#</div><div id="Enter" class="s_key">Enter</div></div><div class="row"><div id="L_Shift" class="s_key">Shift</div><div class="key">\</div><div class="key">Z</div><div class="key">X</div><div class="key">C</div><div class="key">V</div><div class="key">B</div><div class="key">N</div><div class="key">M</div><div class="key">,</div><div class="key">.</div><div class="key">/</div><div id="R_Shift" class="s_key">Shift</div></div><div class="row"><div id="L_Ctrl" class="s_key">Ctrl</div><div id="L_Win" class="s_key Win">Win</div><div id="Alt" class="s_key">Alt</div><div id="Space" class="s_key">Space</div><div id="Alt_Gr" class="s_key">Alt Gr</div><div id="R_Win" class="s_key">Win</div><div id="Menu" class="s_key">&nbsp</div><div id="R_Ctrl" class="s_key">Ctrl</div></div>';

DefaultSettings = {
		logUsage: {
			id:"logUsage",
			name: "Log Usage",
			type: "option",
			def: false,
			description: ""
		},
		rightClick: {
			id:"rightClick",
			name: "Right Click Menu",
			type: "option",
			def: true,
			description: ""
		},
		downloadFiles: {
			id:"downloadFile",
			name: "Download Files",
			type: "keyboard-shortcut",
			def: "",
			description: ""
		},
		selectAll: {
			id:"selectAll",
			name: "Select All Files",
			type: "keyboard-shortcut",
			def: "",
			description: ""
        }
}
		
